import * as fs from 'fs';
import { NormalizedFinding, EvidenceMode } from './types';
import { parseKeyValueArgs, truncate, truncateLines } from './utils';
import { stripCodeCarryingFieldsMinimal } from './strip-code-context';

/**
 * DLP-safe threshold: diff-context values at or below this size were
 * generated by the controlled `generate-diff-context.ts` module and are
 * safe to keep regardless of evidence mode.
 */
const DLP_SAFE_DIFF_LIMIT = 500;

/** Returns true when a diffContext value is small enough to be DLP-safe. */
function isDlpSafeDiff(value: string | null | undefined): boolean {
  return typeof value === 'string' && value.length > 0 && value.length <= DLP_SAFE_DIFF_LIMIT;
}

function applyMinimal(finding: NormalizedFinding): NormalizedFinding {
  const stripped = stripCodeCarryingFieldsMinimal(finding);
  // Preserve DLP-safe diff context — it was intentionally generated
  // with a hard cap of 500 chars and is safe to keep.
  if (isDlpSafeDiff(finding.diffContext)) {
    stripped.diffContext = finding.diffContext;
  }
  return stripped;
}

function applyStandard(finding: NormalizedFinding): NormalizedFinding {
  return {
    ...finding,
    snippet: truncateLines(finding.snippet, 15, 2000),
    // Preserve DLP-safe diff context; strip larger values.
    diffContext: isDlpSafeDiff(finding.diffContext) ? finding.diffContext : null,
    patchSuggestion: null,
    ideFixPrompt: null,
    sarifCodeFlows: null,
    sarifRelatedLocations: null,
  };
}

function applyRich(finding: NormalizedFinding): NormalizedFinding {
  return {
    ...finding,
    snippet: truncateLines(finding.snippet, 30, 2000),
    diffContext: truncate(finding.diffContext, 5000),
    patchSuggestion: truncate(finding.patchSuggestion, 3000),
    ideFixPrompt: truncate(finding.ideFixPrompt, 500),
  };
}

export function applyEvidenceMode(
  findings: NormalizedFinding[],
  mode: EvidenceMode,
): NormalizedFinding[] {
  if (mode === 'MINIMAL') {
    return findings.map((finding) => applyMinimal(finding));
  }
  if (mode === 'STANDARD') {
    return findings.map((finding) => applyStandard(finding));
  }
  return findings.map((finding) => applyRich(finding));
}

function runCli(): void {
  const args = parseKeyValueArgs(process.argv.slice(2));
  const inputPath = args.input;
  const outputPath = args.output;
  const mode = (args.mode || 'MINIMAL').toUpperCase() as EvidenceMode;

  if (!inputPath || !outputPath) {
    throw new Error('Usage: apply-evidence-mode.ts --mode=MINIMAL --input=<file> --output=<file>');
  }

  const payload = JSON.parse(fs.readFileSync(inputPath, 'utf8')) as NormalizedFinding[];
  const transformed = applyEvidenceMode(payload, mode);
  fs.writeFileSync(outputPath, `${JSON.stringify(transformed, null, 2)}\n`, 'utf8');
}

if (require.main === module) {
  runCli();
}
